import { categoryFromSafeSignals, classifyCompilerError, classifyRuntimeError } from "./classifier";
import type { DiagnoseExecutionInput, ExecutionDiagnosis } from "./types";
const result = (value: ExecutionDiagnosis) => value;
export function diagnoseExecution({ execution, attemptAnalysis }: DiagnoseExecutionInput): ExecutionDiagnosis {
  if (execution.outcome === "NOT_RUN") return result({ outcome: "NOT_RUN", secondaryCategories: [], summary: "No matching execution evidence is available for the current code.", evidence: [], suspiciousCodeRegions: [], confidence: 1, safeFailureCategories: [] });
  if (execution.outcome === "COMPILE_ERROR") { const classified = classifyCompilerError(execution.compileOutput); return result({ outcome: execution.outcome, primaryCategory: classified.category, secondaryCategories: [], summary: classified.summary, evidence: [{ source: "COMPILER", description: execution.compileOutput || "The compiler rejected the program." }], suspiciousCodeRegions: [], confidence: classified.confidence, safeFailureCategories: [] }); }
  if (execution.outcome === "RUNTIME_ERROR") { const classified = classifyRuntimeError(execution.runtimeOutput); return result({ outcome: execution.outcome, primaryCategory: classified.category, secondaryCategories: [], summary: "The program terminated during execution.", likelyCause: classified.likelyCause, evidence: [{ source: "RUNTIME", description: execution.runtimeOutput || "The runtime reported abnormal termination." }], suspiciousCodeRegions: attemptAnalysis.suspiciousCodeRegions, confidence: classified.confidence, safeFailureCategories: [] }); }
  if (execution.outcome === "TIME_LIMIT_EXCEEDED") { const complexitySignal = /O\([^)]*(?:n\s*\^?\s*2|n²|2\^n|n!)/i.test(attemptAnalysis.estimatedTimeComplexity ?? "") || /nested/i.test(attemptAnalysis.approachDetected ?? "") || attemptAnalysis.issues.some((issue) => issue.type === "COMPLEXITY"); return result({ outcome: execution.outcome, primaryCategory: complexitySignal ? "TIME_COMPLEXITY" : "UNKNOWN", secondaryCategories: [], summary: complexitySignal ? "The execution exceeded its time limit and the statically detected approach is a likely contributor." : "The execution exceeded its time limit, but the precise cause is uncertain.", evidence: [{ source: "RUNTIME", description: "The trusted execution result reported a time limit exceeded." }, ...(complexitySignal ? [{ source: "STATIC_ANALYSIS" as const, description: `Static analysis estimated ${attemptAnalysis.estimatedTimeComplexity ?? attemptAnalysis.approachDetected ?? "an expensive approach"}.` }] : [])], likelyCause: complexitySignal ? "The current approach likely performs too much repeated work for the input limits." : undefined, suspiciousCodeRegions: attemptAnalysis.suspiciousCodeRegions, confidence: complexitySignal ? .94 : .75, safeFailureCategories: [] }); }
  if (execution.outcome === "ACCEPTED") return result({ outcome: "ACCEPTED", secondaryCategories: [], summary: execution.source === "SUBMIT" ? "The latest matching submission passed all configured tests." : "The latest matching run completed successfully.", evidence: [{ source: execution.source === "SUBMIT" ? "HIDDEN_TEST_SUMMARY" : "VISIBLE_TEST", description: execution.source === "SUBMIT" ? "All configured tests passed." : "The run completed successfully." }], suspiciousCodeRegions: [], confidence: 1, safeFailureCategories: [] });
  if (execution.outcome === "PARTIALLY_CORRECT" || execution.outcome === "WRONG_ANSWER") { const category = categoryFromSafeSignals(execution) ?? (attemptAnalysis.issues.some((issue) => issue.type === "EDGE_CASE") ? "EDGE_CASE" : "LOGIC"); const tests = execution.hiddenTests; return result({ outcome: execution.outcome, primaryCategory: category, secondaryCategories: category === "LOGIC" ? [] : ["LOGIC"], summary: tests ? `${tests.passed} of ${tests.total} hidden tests passed; the remaining failures indicate a likely ${category.toLowerCase().replaceAll("_", " ")} issue.` : "The output did not match expected results, but the exact cause is uncertain.", evidence: [...(tests ? [{ source: "HIDDEN_TEST_SUMMARY" as const, description: `${tests.passed} of ${tests.total} configured tests passed; no secret test data is included.` }] : []), ...(attemptAnalysis.summary ? [{ source: "STATIC_ANALYSIS" as const, description: attemptAnalysis.summary }] : [])], likelyCause: category === "LOGIC" ? "A logic condition or state update likely differs on some cases." : `Safe failure categories point toward ${category.toLowerCase().replaceAll("_", " ")}.`, suspiciousCodeRegions: attemptAnalysis.suspiciousCodeRegions, confidence: execution.safeFailureCategories.length ? .9 : .72, safeFailureCategories: execution.safeFailureCategories }); }
  return result({ outcome: "UNKNOWN", secondaryCategories: [], summary: "Execution information was available, but the failure could not be diagnosed reliably.", evidence: [], suspiciousCodeRegions: [], confidence: 0, safeFailureCategories: [] });
}
