import assert from "node:assert/strict";
import test from "node:test";
import { analyzeStudentAttemptCore } from "../src/lib/tutor/analyzer/engine";
import { collectPreAnalysisSignals } from "../src/lib/tutor/analyzer/heuristics";
import { StudentAttemptAnalysisSchema } from "../src/lib/tutor/analyzer/schema";
import { buildTutorSystemPrompt } from "../src/lib/tutor/prompt";

const problem = { title: "Pair Sum", statement: "Find two values.", constraints: ["n >= 2"], examples: [{ input: "[2,7], 9", output: "[0,1]" }], topics: ["Arrays"], expectedTimeComplexity: "O(n)", canonicalPatterns: ["Hashing"], commonMistakes: ["duplicate handling"] };
test("empty and untouched starter code skip model analysis", async () => { let calls = 0; const generate = async () => { calls += 1; return "{}"; }; const empty = await analyzeStudentAttemptCore({ problem, language: "cpp", code: "   " }, generate); const untouched = await analyzeStudentAttemptCore({ problem, language: "cpp", code: "int solve() { return 0; }", starterCode: "int solve() { return 0; }" }, generate); assert.equal(empty.attemptState, "EMPTY"); assert.equal(empty.codeCompleteness, 0); assert.equal(untouched.attemptState, "EMPTY"); assert.equal(calls, 0); });
test("schema supports partial attempts and normalizes confidence", () => { const result = StudentAttemptAnalysisSchema.parse({ attemptState: "PARTIAL", approachDetected: "nested-loop search", codeCompleteness: 0.4, issues: [], conceptsUnderstood: ["array traversal"], possibleKnowledgeGaps: [], suspiciousCodeRegions: [], summary: "A loop exists but core logic is unfinished.", confidence: 1.7 }); assert.equal(result.attemptState, "PARTIAL"); assert.equal(result.confidence, 1); });
test("invalid model output returns safe unknown analysis", async () => { const result = await analyzeStudentAttemptCore({ problem, language: "cpp", code: "for (int i=0; i<n; i++) work(i);" }, async () => "not json"); assert.equal(result.attemptState, "UNKNOWN"); assert.equal(result.confidence, 0); });
test("heuristics detect reusable brute-force signals", () => { const signals = collectPreAnalysisSignals("for (int i=0;i<n;i++) { for (int j=i+1;j<n;j++) {} }"); assert.equal(signals.nestedLoops, true); assert.ok(signals.meaningfulStatementCount > 0); });
test("analysis schema cannot own hint level", () => { const parsed = StudentAttemptAnalysisSchema.safeParse({ attemptState: "PARTIAL", codeCompleteness: .5, issues: [], conceptsUnderstood: [], possibleKnowledgeGaps: [], suspiciousCodeRegions: [], summary: "Partial", confidence: .5, hintLevel: 3 }); assert.equal(parsed.success, false); });
test("Phase 1 policy remains authoritative over analyzer context", () => { const prompt = buildTutorSystemPrompt({ hintLevel: 0, codeProvided: true, attemptAnalysis: "Detected approach: brute force\nPossible knowledge gaps: hashing", problem: { id: "p", title: "Pair Sum", description: "Find a pair", constraints: [], topics: ["hashing"], guidanceHints: [] } }); assert.match(prompt, /optimal algorithm or data-structure names/); assert.match(prompt, /policy above always takes precedence/); });
