import assert from "node:assert/strict";
import test from "node:test";
import { diagnoseExecution } from "../src/lib/tutor/diagnosis/engine";
import { discardStaleExecution, normalizeExecutionResult } from "../src/lib/tutor/diagnosis/normalize";
import { hashStudentCode } from "../src/lib/tutor/diagnosis/hash";
import { buildTutorSystemPrompt } from "../src/lib/tutor/prompt";
import type { StudentAttemptAnalysis } from "../src/lib/tutor/analyzer/types";

const attempt: StudentAttemptAnalysis = { attemptState: "PARTIAL", approachDetected: "nested-loop brute force", codeCompleteness: .8, issues: [{ type: "COMPLEXITY", severity: "HIGH", description: "Nested traversal repeats searches." }], conceptsUnderstood: ["array traversal"], possibleKnowledgeGaps: ["efficient lookup"], suspiciousCodeRegions: [], estimatedTimeComplexity: "O(n^2)", summary: "The attempt uses nested loops.", confidence: .9 };
test("compile syntax errors are classified deterministically", () => { const diagnosis = diagnoseExecution({ execution: normalizeExecutionResult({ source: "RUN", status: "compile_error", stderr: "main.cpp:12: error: expected ';' before '}'" }), attemptAnalysis: attempt }); assert.equal(diagnosis.outcome, "COMPILE_ERROR"); assert.equal(diagnosis.primaryCategory, "SYNTAX"); });
test("segmentation faults are classified as likely invalid access", () => { const diagnosis = diagnoseExecution({ execution: normalizeExecutionResult({ source: "RUN", status: "runtime_error", stderr: "SIGSEGV" }), attemptAnalysis: attempt }); assert.equal(diagnosis.outcome, "RUNTIME_ERROR"); assert.equal(diagnosis.primaryCategory, "OUT_OF_BOUNDS"); assert.match(diagnosis.likelyCause ?? "", /likely/i); });
test("TLE combines authoritative timeout with static complexity evidence", () => { const diagnosis = diagnoseExecution({ execution: normalizeExecutionResult({ source: "SUBMIT", verdict: "TIME_LIMIT_EXCEEDED", passedCases: 3, totalCases: 10 }), attemptAnalysis: attempt }); assert.equal(diagnosis.primaryCategory, "TIME_COMPLEXITY"); assert.ok(diagnosis.confidence >= .9); });
test("partial hidden summary uses only safe boundary category", () => { const diagnosis = diagnoseExecution({ execution: normalizeExecutionResult({ source: "SUBMIT", verdict: "WRONG_ANSWER", passedCases: 13, totalCases: 15, safeFailureCategories: ["boundary"] }), attemptAnalysis: attempt }); assert.equal(diagnosis.outcome, "PARTIALLY_CORRECT"); assert.equal(diagnosis.primaryCategory, "BOUNDARY"); assert.doesNotMatch(JSON.stringify(diagnosis), /expectedOutput|hiddenOutput|"input"/); });
test("accepted evidence does not invent a bug", () => { const diagnosis = diagnoseExecution({ execution: normalizeExecutionResult({ source: "SUBMIT", verdict: "ACCEPTED", passedCases: 15, totalCases: 15 }), attemptAnalysis: attempt }); assert.equal(diagnosis.outcome, "ACCEPTED"); assert.equal(diagnosis.primaryCategory, undefined); assert.equal(diagnosis.confidence, 1); });
test("stale execution evidence is ignored by code hash", () => { const execution = normalizeExecutionResult({ source: "RUN", status: "runtime_error", codeHash: hashStudentCode("old") }); assert.equal(discardStaleExecution(execution, hashStudentCode("new")).outcome, "NOT_RUN"); });
test("missing execution becomes NOT_RUN", () => assert.equal(normalizeExecutionResult().outcome, "NOT_RUN"));
test("compiler paths are sanitized and truncated", () => { const value = normalizeExecutionResult({ source: "RUN", status: "compile_error", stderr: "/home/ubuntu/judge/submission/main.cpp:8: error: expected ';'" }); assert.doesNotMatch(value.compileOutput ?? "", /home\/ubuntu/); assert.match(value.compileOutput ?? "", /main.cpp:8/); });
test("Phase 1 policy still forbids direct corrections at level zero", () => { const prompt = buildTutorSystemPrompt({ hintLevel: 0, codeProvided: true, executionDiagnosis: "Primary category: BOUNDARY; likely loop condition error", problem: { id: "p", title: "P", description: "D", constraints: [], topics: [], guidanceHints: [] } }); assert.match(prompt, /pseudocode.*code/); assert.match(prompt, /policy above remains authoritative/); });
