"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Search, ArrowUpRight } from "lucide-react";
import { AppShell } from "@/components/app-shell/AppShell";
type Row={slug:string;title:string;difficulty:"Easy"|"Medium"|"Hard";topics:string[];status:"solved-independent"|"solved-guidance"|"not-attempted";guidanceUsed:string;lastAttempt:string|null};
export function DatabaseProblemsPage(){const [rows,setRows]=useState<Row[]>([]),[search,setSearch]=useState(""),[difficulty,setDifficulty]=useState("All"),[topic,setTopic]=useState("All"),[status,setStatus]=useState("All"),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/problems").then(r=>r.ok?r.json():Promise.reject()).then(d=>setRows(d.problems)).catch(()=>setError("Unable to load the problem bank."));},[]);
 const topics=useMemo(()=>["All",...Array.from(new Set(rows.flatMap(r=>r.topics)))],[rows]);const filtered=rows.filter(r=>(!search||r.title.toLowerCase().includes(search.toLowerCase())||r.topics.some(t=>t.toLowerCase().includes(search.toLowerCase())))&&(difficulty==="All"||r.difficulty===difficulty)&&(topic==="All"||r.topics.includes(topic))&&(status==="All"||r.status===status));
 return <AppShell><div className="p-6 md:p-10 max-w-7xl mx-auto space-y-8"><div className="border-b border-smoky/10 pb-6"><span className="font-mono text-xs text-olive tracking-widest">PROBLEM CURRICULUM</span><h1 className="text-4xl font-bold text-smoky">Problems</h1><p className="text-sm text-olive">Practice individually or follow a structured pattern trajectory.</p></div>
 <div className="flex flex-wrap gap-3"><div className="relative w-80"><Search className="w-4 h-4 absolute left-3 top-2.5 text-olive"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search problems or topics…" className="w-full pl-9 pr-3 py-2 rounded border border-smoky/15 bg-bone/30 font-mono text-xs"/></div>{[["Difficulty",difficulty,setDifficulty,["All","Easy","Medium","Hard"]],["Topic",topic,setTopic,topics],["Status",status,setStatus,["All","not-attempted","solved-guidance","solved-independent"]]].map(([label,value,setter,options])=><select key={label as string} aria-label={label as string} value={value as string} onChange={e=>(setter as (x:string)=>void)(e.target.value)} className="px-3 py-2 rounded border border-smoky/15 bg-bone/30 font-mono text-xs">{(options as string[]).map(x=><option key={x}>{x}</option>)}</select>)}</div>
 <div className="overflow-x-auto rounded-[24px] border border-smoky/15 bg-floral shadow-lg"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-smoky/15 font-mono text-xs text-olive"><th className="p-4">STATUS</th><th>PROBLEM</th><th>DIFFICULTY</th><th>TOPICS</th><th>GUIDANCE</th><th>LAST ATTEMPT</th></tr></thead><tbody>{filtered.map(r=><tr key={r.slug} className="border-b border-smoky/10 hover:bg-bone/30"><td className="p-4 text-xs font-mono">{r.status.replaceAll("-"," ")}</td><td><Link href={`/problems/${r.slug}`} className="font-semibold flex items-center gap-2">{r.title}<ArrowUpRight className="w-3 h-3"/></Link></td><td>{r.difficulty}</td><td>{r.topics.join(", ")}</td><td>{r.guidanceUsed}</td><td>{r.lastAttempt?new Date(r.lastAttempt).toLocaleDateString():"—"}</td></tr>)}</tbody></table>{error&&<p className="p-6 text-sm">{error}</p>}</div></div></AppShell>}
