"use client";
import { useEffect, useRef, useState } from "react";
import { Brain, Code2, LoaderCircle, Send, Sparkles } from "lucide-react";
type ChatMessage = { id: string; role: "student" | "tutor"; content: string };
const actions = [["Give me a hint", "Give me a hint"], ["Another hint", "Give me another hint"], ["Explain concept", "I don't understand the concept. Explain it without giving away the solution."], ["Give approach", "Give me the approach"], ["Implementation help", "Help me implement one part of this"]] as const;
const ERROR_MESSAGE = "The tutor couldn't respond right now. Your code and progress are safe — try again.";
export function TutorChatPanel({ problemId, code }: { problemId: string; code: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]), [input, setInput] = useState(""), [loading, setLoading] = useState(false), [includeCode, setIncludeCode] = useState(false); const [sessionId, setSessionId] = useState<string>(); const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => { setMessages([{ id: crypto.randomUUID(), role: "tutor", content: "Tell me what you've tried or ask for a hint. I'll give you the smallest useful next step." }]); setSessionId(undefined); setInput(""); }, [problemId]);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, loading]);
  async function send(message: string) { const trimmed = message.trim(); if (!trimmed || loading) return; setInput(""); setLoading(true); setMessages((items) => [...items, { id: crypto.randomUUID(), role: "student", content: trimmed }]); try { const response = await fetch("/api/tutor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ problemId, message: trimmed, language: "cpp", sessionId, ...(includeCode ? { code } : {}) }) }); const payload = await response.json() as { message?: string; sessionId?: string }; if (!response.ok || !payload.message) throw new Error(); setSessionId(payload.sessionId); setMessages((items) => [...items, { id: crypto.randomUUID(), role: "tutor", content: payload.message! }]); } catch { setMessages((items) => [...items, { id: crypto.randomUUID(), role: "tutor", content: ERROR_MESSAGE }]); } finally { setLoading(false); } }
  return <div className="h-full bg-smoky text-floral flex flex-col font-sans"><div className="p-4 border-b border-bone/20"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Brain className="w-4 h-4"/><strong className="text-sm">AlgoTrace Tutor</strong></div><span className="font-mono text-[10px] text-bone/60">SOCRATIC GUIDE</span></div><p className="mt-2 text-xs text-bone/65">Guidance grows only when you need it. Your next attempt stays yours.</p></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{messages.map((message) => <div key={message.id} className={message.role === "student" ? "flex justify-end" : "flex justify-start"}><div className={`max-w-[90%] rounded-lg border px-3 py-2 text-xs leading-5 whitespace-pre-wrap ${message.role === "student" ? "bg-bone text-smoky border-bone" : "bg-[#171812] text-bone border-bone/20"}`}>{message.role === "tutor" && <Sparkles className="inline w-3 h-3 mr-1"/>}{message.content}</div></div>)}{loading && <div className="flex items-center gap-2 text-xs text-bone/60"><LoaderCircle className="w-3 h-3 animate-spin"/>Thinking about the smallest useful hint…</div>}<div ref={bottomRef}/></div><div className="border-t border-bone/20 p-3 space-y-3"><div className="flex gap-1.5 overflow-x-auto">{actions.map(([label,message]) => <button key={label} disabled={loading} onClick={() => void send(message)} className="shrink-0 border border-bone/25 rounded-full px-2.5 py-1 font-mono text-[10px] text-bone/80 hover:bg-bone hover:text-smoky disabled:opacity-50">{label}</button>)}</div><button onClick={() => setIncludeCode((value) => !value)} className={`flex items-center gap-1.5 font-mono text-[10px] ${includeCode ? "text-floral" : "text-bone/55"}`}><Code2 className="w-3 h-3"/>{includeCode ? "Current code will be shared" : "Share current code with next message"}</button><form onSubmit={(event) => { event.preventDefault(); void send(input); }} className="flex gap-2"><input value={input} maxLength={2000} disabled={loading} onChange={(event) => setInput(event.target.value)} placeholder="Where are you stuck?" className="min-w-0 flex-1 bg-[#171812] border border-bone/25 rounded px-3 py-2 text-xs outline-none focus:border-bone/60 disabled:opacity-60"/><button disabled={loading || !input.trim()} className="bg-bone text-smoky rounded px-3 disabled:opacity-40" aria-label="Send to tutor"><Send className="w-4 h-4"/></button></form></div></div>;
}
