import { TutorDecisionSchema } from "./schema";
import { constrainAction } from "./rules";
import type { DecideTutorActionInput, TutorAction, TutorDecision } from "./types";
export const SAFE_TUTOR_DECISION: TutorDecision = { action: "SAFE_FALLBACK", objective: "Ask the student to inspect the current reasoning and try a small dry run.", reasoningMode: "SOCRATIC", shouldReferenceExecution: false, shouldReferenceCode: true, shouldAskForAnotherAttempt: true, confidence: 0 };
const objectiveFor: Record<TutorAction, string> = { ASK_REASONING_QUESTION: "Establish the student's current reasoning before offering direction.", ASK_COMPLEXITY_QUESTION: "Help the student notice repeated work and estimate its cost.", ASK_DRY_RUN: "Help the student locate where observed behavior first diverges.", POINT_TO_CODE_REGION: "Direct attention to the relevant code region without correcting it outright.", POINT_TO_FAILURE_TYPE: "Help the student understand the kind of execution failure blocking progress.", EXPLAIN_CONCEPT: "Teach the missing concept within the permitted reveal limit.", COMPARE_ALTERNATIVES: "Help the student compare tradeoffs between plausible approaches.", GUIDE_EDGE_CASE_REASONING: "Help the student reason about an unhandled class of edge cases.", GUIDE_BOUNDARY_REASONING: "Help the student inspect bounds and stopping conditions.", GUIDE_STATE_REASONING: "Help the student verify how state changes across iterations.", GUIDE_COMPLEXITY_IMPROVEMENT: "Help the student reduce repeated work without exceeding the reveal limit.", PROVIDE_APPROACH_DIRECTION: "Point toward the relevant algorithmic direction.", PROVIDE_PSEUDOCODE: "Provide a structured implementation plan without complete code.", PROVIDE_CODE_FRAGMENT: "Resolve one narrow implementation blockage with a small fragment.", ASK_STUDENT_TO_TRY_AGAIN: "Turn the current insight into another independent attempt.", ASK_REFLECTION: "Help the student articulate why the successful approach works.", ACKNOWLEDGE_SUCCESS: "Recognize the verified result and invite brief reflection.", CLARIFY_STUDENT_QUESTION: "Clarify what the student wants to understand before intervening.", SAFE_FALLBACK: SAFE_TUTOR_DECISION.objective };
function choose(input: DecideTutorActionInput): { action: TutorAction; focus?: string; confidence: number; execution: boolean; code: boolean } {
  const { executionDiagnosis: d, attemptAnalysis: a } = input; const category = d.primaryCategory;
  if (d.outcome === "ACCEPTED") return { action: input.studentIntent === "QUESTION" ? "ASK_REFLECTION" : "ACKNOWLEDGE_SUCCESS", focus: "verified solution", confidence: 1, execution: true, code: false };
  if (d.outcome === "COMPILE_ERROR") return { action: d.suspiciousCodeRegions.length || d.evidence.some((e) => /line\s+\d+/i.test(e.description)) ? "POINT_TO_CODE_REGION" : "POINT_TO_FAILURE_TYPE", focus: category?.toLowerCase(), confidence: d.confidence, execution: true, code: true };
  if (d.outcome === "RUNTIME_ERROR") return { action: category === "OUT_OF_BOUNDS" || category === "NULL_OR_INVALID_ACCESS" ? "GUIDE_BOUNDARY_REASONING" : category === "STACK_OVERFLOW" ? "GUIDE_STATE_REASONING" : d.confidence < .7 ? "ASK_DRY_RUN" : "POINT_TO_FAILURE_TYPE", focus: category?.toLowerCase(), confidence: d.confidence, execution: true, code: true };
  if (d.outcome === "TIME_LIMIT_EXCEEDED") return { action: category === "TIME_COMPLEXITY" ? "GUIDE_COMPLEXITY_IMPROVEMENT" : "ASK_COMPLEXITY_QUESTION", focus: "repeated work", confidence: d.confidence, execution: true, code: true };
  if (d.outcome === "PARTIALLY_CORRECT" || d.outcome === "WRONG_ANSWER") return { action: category === "BOUNDARY" ? "GUIDE_BOUNDARY_REASONING" : category === "DUPLICATE_HANDLING" || category === "EDGE_CASE" ? "GUIDE_EDGE_CASE_REASONING" : d.suspiciousCodeRegions.length && d.confidence >= .75 ? "POINT_TO_CODE_REGION" : "ASK_DRY_RUN", focus: category?.toLowerCase(), confidence: d.confidence, execution: true, code: true };
  if (a.attemptState === "EMPTY") return { action: "ASK_REASONING_QUESTION", focus: "problem intuition", confidence: 1, execution: false, code: false };
  if (input.studentIntent === "NEED_CODE_HELP" && input.hintLevel >= 5) return { action: "PROVIDE_CODE_FRAGMENT", focus: a.issues[0]?.description, confidence: a.confidence, execution: false, code: true };
  if (input.studentIntent === "NEED_PSEUDOCODE") return { action: "PROVIDE_PSEUDOCODE", focus: a.approachDetected, confidence: a.confidence, execution: false, code: true };
  const implementationIssue = a.issues.find((issue) => issue.type === "IMPLEMENTATION" || issue.type === "LOGIC");
  if (implementationIssue && a.conceptsUnderstood.length) return { action: a.suspiciousCodeRegions.length ? "POINT_TO_CODE_REGION" : "ASK_DRY_RUN", focus: implementationIssue.description, confidence: a.confidence, execution: false, code: true };
  if (a.possibleKnowledgeGaps.length && input.hintLevel >= 2) return { action: "EXPLAIN_CONCEPT", focus: a.possibleKnowledgeGaps[0], confidence: a.confidence, execution: false, code: true };
  if (a.attemptState === "PARTIAL") return { action: input.session.codeChangedSinceLastHint ? "ASK_STUDENT_TO_TRY_AGAIN" : "ASK_REASONING_QUESTION", focus: a.approachDetected, confidence: a.confidence, execution: false, code: true };
  return { action: input.studentIntent === "QUESTION" ? "CLARIFY_STUDENT_QUESTION" : "ASK_REASONING_QUESTION", confidence: Math.max(.4, a.confidence), execution: false, code: Boolean(a.codeCompleteness) };
}
export function decideTutorAction(input: DecideTutorActionInput): TutorDecision { try { let candidate = choose(input); let action = constrainAction(candidate.action, input.hintLevel); if (action === input.session.previousAction && input.studentIntent === "MORE_HELP") { const escalation: Partial<Record<TutorAction, TutorAction>> = { ASK_COMPLEXITY_QUESTION: "GUIDE_COMPLEXITY_IMPROVEMENT", ASK_REASONING_QUESTION: "ASK_DRY_RUN", ASK_DRY_RUN: "POINT_TO_CODE_REGION" }; action = constrainAction(escalation[action] ?? action, input.hintLevel); } const decision = { action, objective: objectiveFor[action], focus: candidate.focus, targetIssue: candidate.focus, targetCodeRegion: input.attemptAnalysis.suspiciousCodeRegions[0], reasoningMode: action === "ACKNOWLEDGE_SUCCESS" || action === "ASK_REFLECTION" ? "REFLECTIVE" as const : candidate.execution ? "DIAGNOSTIC" as const : action === "EXPLAIN_CONCEPT" ? "EXPLANATORY" as const : "SOCRATIC" as const, recommendedPromptStyle: "Be concise, natural, and never mention internal decision metadata.", shouldReferenceExecution: candidate.execution, shouldReferenceCode: candidate.code, shouldAskForAnotherAttempt: !["ACKNOWLEDGE_SUCCESS", "ASK_REFLECTION", "CLARIFY_STUDENT_QUESTION"].includes(action), confidence: candidate.confidence }; return TutorDecisionSchema.parse(decision); } catch { return SAFE_TUTOR_DECISION; } }
